version: '3.2'
services:
  orion-web:
    build: .
    environment:
    - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    ports:
     - "8080:80"
    links:
     - orion-sql
    volumes:   
     - type: bind
       source: ${SQL_DATA_DIR}
       target: /app/sql-data
    depends_on:
     - orion-sql
    labels:
     - "build.no=${BUILD_STAMP}"
  orion-sql:
    image: "microsoft/mssql-server-linux:2017-CU12"
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=${SA_PASSWORD}
     - MSSQL_PID=Express
    volumes:     
     - type: bind
       source: ${SQL_DATA_DIR}
       target: /var/opt/mssql
    ports:
     - "1533:1433"
    labels:
     - "build.no:=${BUILD_STAMP}"
env_file: .env