version: '3'
services:
  orion-web:
    build: .
    environment:
    - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
    ports:
     - "80:80"
     - "443:443"
    links:
     - orion-sql
    volumes:     
     - ./sql-mount-001:/mssql
    depends_on:
     - orion-sql
  orion-sql:
    image: "microsoft/mssql-server-linux:2017-CU12"
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=${SA_PASSWORD}
     - MSSQL_PID=Express
    volumes:     
     - ./sql-mount-001:/var/opt/mssql
    ports:
     - "1433:1433"